language: scala

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2

before_script:
  npm install -g snyk

script:
- sbt coverage test
- sbt reportTestCov
- sbt talosMicrosite/tut