version: '3'

services:
  talos-gateway:
    build: ./gateway
    ports:
      - "8080:8080"

  cats-service-a:
    image: rodolpheche/wiremock
    container_name: cats-service-a
    ports:
      - "9002:8080"
    volumes:
      - ./services/cats/mockdata/stubs:/home/wiremock:z

  cats-service-b:
    image: rodolpheche/wiremock
    container_name: cats-service-b
    ports:
    - "9003:8080"
    volumes:
    - ./services/cats/mockdata/stubs:/home/wiremock:z

  dogs-service-a:
    container_name: dogs-service-a
    image: rodolpheche/wiremock
    ports:
      - "9001:8080"
    volumes:
      - ./services/dogs/mockdata/stubs:/home/wiremock:z

  dogs-service-b:
    container_name: dogs-service-b
    image: rodolpheche/wiremock
    ports:
    - "9000:8080"
    volumes:
    - ./services/dogs/mockdata/stubs:/home/wiremock:z