version: '3'

services:
  talos-demo:
    image:  vaslabs/talos-demo:SNAPSHOT
    hostname: talos
    container_name: "talos-demo"
    ports:
      - "8080:8080"
      - "5266:5266" # Kamon status
      - "9095:9095" # Prometheus metrics
